config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root                    'static_pages#home'
  get    'help'        => 'static_pages#help'
  get    'link'        => 'static_pages#link'
  get    'about'       => 'static_pages#about'
  get    'contact'     => 'static_pages#contact'
  get    'signup'      => 'users#new'
  get    'login'       => 'sessions#new'
  post   'login'       => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'
  get    'attend_edit' => 'users#attend_edit'
  
  # get '/users/:id/:update_id/:departure_flag' => 'users#show'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      # 検索拡張機能として.search(params[:search])を追加 
      @feed_items = current_user.feed.paginate(page: params[:page]).search(params[:search])
    end
  end

  def link
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_user_logged_in.html.erb
<% provide(:search_name) %>
<% provide(:path, root_path) %>
  <div class="row">
<!--(中略)-->
    <div class="col-md-8">
      <h3>ツイート内容の検索</h3>
      <%= render 'users/search' %>  
      <%= render 'shared/feed' %>
      <!--<%= render 'shared/feed' %>-->
    </div>
  </div>
  
  

app/views/static_pages/about.html.erb
<% provide(:title, "管理人紹介") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | kenko-portfolio</title>
  </head>
  <body>
    <h1>管理人</h1>
    <p>
      <!--<a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>-->
      <!--is a <a href="https://railstutorial.jp/#ebook">book</a> and-->
      <!--<a href="https://railstutorial.jp/#screencast">screencast</a>-->
      <!--to teach web development with-->
      <!--<a href="http://rubyonrails.org/">Ruby on Rails</a>.-->
      <!--This is the sample application for the tutorial.-->
      
      <p>氏名：金子 秀平<p>
      <p>生年月日：１９８２年７月９日<p>
      <p>出身地：愛知県豊橋市<p>
        
      <p>自己紹介<p>
      <p>豊橋市生まれの豊橋市育ち。愛知県立豊橋工業高等学校卒業後、地元企業の東洋製罐豊橋工場へ就職し<p>  
      <p>ラインオペレーターとして16年間従事する。業務改善として独学でMS Excel/Access VBAを勉強。<p>  
      <p>上司へ嘆願しシステム部へ移動し1年半従事する。<p>  
      <p>社内のDB・ネットワーク・ハードウェア等の保守管理や社内各課の要望をヒアリングしシステム開発業務を行った。<p>  
      <p>実際に作成した成果物として生産実績出力や材料照合システムなどのプログラムを作成。言語はMS Excel/Access<p>  
      <p>又、プログラミングに興味を持ちプライベートの時間を活用してプログラミングの勉強を進めている。その他にも筋トレにハマり<p>  
      <p>ジムのトレーナーの進めでコンテストに挑戦もしていたがプログラミング勉強に注力している為、現在順調にリバウンド中。<p>  
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>ヘルプ</h1>
    <p>  Get help on the Ruby on Rails Tutorial at the
      <a href="https://railstutorial.jp/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="https://railstutorial.jp/#ebook">
      <em>Ruby on Rails Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "ホーム") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <!--<div class="col-md-8">-->
    <!--  <h3>ツイート一覧</h3>-->
    <!--  <%= render 'shared/feed' %>-->
    <!--</div>-->
  </div>
  <%= render 'static_pages/user_logged_in' %>
<% else %>

  <div class="center jumbotron">
  <div>
    <h1>勤怠システム</h1>
    <!--<div style="text-align:center;">-->
      <P><%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %></P>
    
      <small>
       <!--アカウント作成は <a href= "home/ec2-user/environment/sample_app/app/views/users/new.html.erb" target="_blank">こちら</a>-->
       アカウント作成は<%= link_to "こちら",signup_path %>
      </small>
    <!--</div>-->
  </div>

  <body>
  </body>

  <!--%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %-->
              

<% end %>

app/views/static_pages/link.html.erb
<% provide(:title, "リンク") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | kenko-portfolio</title>
  </head>
  <body>
    <h1>リンク</h1>
    <div class="center">
      <p><font size="5" color="##000000">管理人が通っていたジム</font></p>
      <%= link_to image_tag('ito_gym_logo.jpg',:size =>'600x300') , 'http://www.itogym.com', :target=>["_blank"] %>
      <h1></h1>
      <h1></h1>  
      <p><font size="5" color="##000000">管理人が出場したコンテスト</font></p>
      <%= link_to image_tag('best_body_j_logo.png', { :border => '0'}) , 'https://www.bestbodyjapan.com', :target=>["_blank"] %>
    </div>
  </body>
</html>