config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root                    'static_pages#home'
  get    'help'        => 'static_pages#help'
  get    'link'        => 'static_pages#link'
  get    'about'       => 'static_pages#about'
  get    'contact'     => 'static_pages#contact'
  get    'signup'      => 'users#new'
  get    'login'       => 'sessions#new'
  post   'login'       => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'
  get    'attend_edit' => 'users#attend_edit'
  
  # get '/users/:id/:update_id/:departure_flag' => 'users#show'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :attendances
  has_many :microposts, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
    # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end
  
  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

<!--<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>-->
<!--  <div><%= hidden_field_tag :followed_id, @user.id %></div>-->
<!--  <%= f.submit "フォロー", class: "btn btn-primary" %>-->
<!--<% end %>-->

app/views/users/_form.html.erb
 
<%=<%=  form_forform_for((@user@user))  dodo  ||ff||  %>%>
     <%=<%=  renderrender  'shared/error_messages''shared/error_messages',,  objectobject::  @user@user  %>%>

      <%=<%=  ff..labellabel  :name:name  %>%>
     <%=<%=  ff..text_fieldtext_field  :name:name,,  classclass::  'form-control''form-control'  %>%>

      <%=<%=  ff..labellabel  :email:email  %>%>
     <%=<%=  ff..email_fieldemail_field  :email:email,,  classclass::  'form-control''form-control'  %>%>

      <%=<%=  ff..labellabel  :password:password  %>%>
     <%=<%=  ff..password_fieldpassword_field  :password:password,,  classclass::  'form-control''form-control'  %>%>

      <%=<%=  ff..labellabel  :password_confirmation:password_confirmation  %>%>
     <%=<%=  ff..password_fieldpassword_field  :password_confirmation:password_confirmation,,  classclass::  'form-control''form-control'  %>%>

      <%=<%=  ff..submitsubmit  yieldyield((:button_text:button_text),),  classclass::  "btn btn-primary""btn btn-primary"  %>%>
 <%<%  endend  %>%>

app/views/users/_search.html.erb
<p><%= yield(:search_name) %></p>
<%= form_tag(yield(:path), method: :get) do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag '検索', :name => nil %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "削除", user, method: :delete,
                                  data: { confirm: "削除しますか?" } %>
  <% end %>
</li>

app/views/users/attend_edit.html.erb
<!DOCTYPE html>
<html>
  <body>
  <table border="1" width="1200">
    <tr align="center">
      <td>日付</td>
      <td>曜日</td>
      <td>出社</td>
      <td>退社</td>
      <td>在社時間</td>
      <td>備考</td>
      <td>残業指示</td>
      <td>指示者</td>
    </tr>
      <% (@first_day.day...@last_day).each do |temp_day| %>
        <tr align="center" height="50">
        <td><%= @first_day.month %>/<%= temp_day %></td>
        <td><%= @attendance.month %>/<%= @attendance.day %>></td>
        <td><%= f.text_field :name, class: 'form-control' %></td>
        </tr>
      <% end %>
  </table> 
  </body>
</html>    

app/views/users/edit.html.erb
<% provide(:title, "アカウント情報の更新") %>
<h1>プロフィール更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メースアドレス %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>

    <!--<div class="gravatar_edit">-->
    <!--  <%= gravatar_for @user %>-->
    <!--  <a href="http://gravatar.com/emails">変更</a>-->
    <!--</div>-->
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '全てのユーザー') %>
<% provide(:search_name, 'ユーザー検索') %>
<% provide(:path, users_path) %>
<h1>全てのユーザー</h1>

<%= will_paginate %>

<ul class="users">
  <%= render 'users/search' %> 
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name,"名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email,"Eメール" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password,"パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>

<body>
 <table border="1" width="1200">
    <tr align="center">
      <td height="45">
        <%= link_to "←", user_path(piyo: @first_day.prev_month),style:"color:white", class: 'btn btn-default btn-primary' %>   
        <%= @first_day.year %>年<%= @first_day.month %>月の時間管理表   
        <%= link_to "→", user_path(piyo: @first_day.next_month),style:"color:white", class: 'btn btn-default btn-primary' %>
        
      </td>
      <td>指定勤務時間 8:00</td>
      <td colspan="3">7:50 基本時間</td>
      <td>初日 <%= @first_day.month %>/<%= @first_day.day %></td>
    </tr>
    <tr align="center">
      <td>所属 <%= @user.affiliation %></td>
      <td>氏名 <%= @user.name %></td>
      <td>コード</td>
      <td width="10"></td>
      <td>出勤日数</td>
      <td>締め <%= @first_day.month %>/<%= @last_day %></td>
    </tr>
    </table> 
</body>
　
　<br><br><br>
　
　<body><%= link_to "勤怠を編集", attend_edit_path, style:"color:white", class: 'btn btn-default btn-primary' %>
　  <table class="s-tbl" border="1" width="1200">
      <tr align="center">
        <td rowspan="2">日付</td>
        <td rowspan="2">曜日</td>
        <td colspan="3">出社</td>
        <td colspan="3">退社</td>
        <td rowspan="2">滞在時間</td>
        <td rowspan="2">備考</td>
        <td rowspan="2">残業指示</td>
        <td rowspan="2">残業指示者</td>
      </tr>
      
      <tr align="center">
        <td>時</td><td>分</td><td width="130"></td><td>時</td><td>分</td><td width="10"></td>
      </tr>

        <% youbi = %w[日 月 火 水 木 金 土] %>
        <% (@first_day.day...@last_day).each do |temp_day| %>
            <tr align="center" height="50">
              <td><%= @first_day.month %>/<%= temp_day %></td>
              <td><%= @youbi [@first_day.change(day: temp_day) .wday] %></td>
              
              
              <td><%# 出勤時間 %>
                  <% @attendance.each do |value| %>
                    <% arrival_h = value[:arrival] %>
                    <%= arrival_h.hour if @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month  && arrival_h.day == temp_day %>
                  <% end %>
              </td>

              <td><%# 出勤分 %>
                  <% @attendance.each do |value| %>
                    <% arrival_m = value[:arrival] %>
                    <%= arrival_m.min if @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month  && arrival_m.day == temp_day %>
                 <% end %>                
              </td>
              <td width="130">
                <%# 今日の年月日だったらボタン表示。年まで条件付けしないと前年や来年等の同月日にボタンが描画されてしまう為。 %>
                <% comparison_date = Date.new(Date.today.year,Date.today.month,temp_day) %>
                <% range = comparison_date.beginning_of_day..comparison_date.end_of_day %>
                <% if @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month  && temp_day ==  @y_m_d.day %>
                  <% if @attendance.where(arrival: range).empty? %>  <%# 今日の出勤情報がモデル内に存在しているか判定 %>
                    <%= link_to "出 勤", user_path(flag: "arrival_flag"), style:"color:white", class: "btn btn-primary" %>
                  <% elsif @attendance.where(departure: range).empty? %>　<%# 退勤情報がモデル内に存在しているか判定 %>
                    <%= link_to "退 勤", user_path(flag: "departure_flag"), style:"color:white", class: "btn btn-primary" %>
                  <% else %>
                    <%# 退勤ボタンを押下済みならボタンは非表示 %>
                  <% end %>
                <% end %>
              </td>
              
              <td><%# 退勤時間 %>
                  <% @attendance.each do |value| %>
                    <% departure_h = value[:departure] %>
                    <% if departure_h != nil %>
                      <%= departure_h.hour if @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month  && departure_h.day == temp_day %>
                    <% end %>
                 <% end %>                
              </td>
              
              <td><%# 退勤分 %>
                  <% @attendance.each do |value| %>
                    <% departure_m = value[:departure] %>
                    <% if departure_m != nil %>
                      <%= departure_m.min if @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month  && departure_m.day == temp_day %>
                    <% end %>
                 <% end %>                     
              </td>
              <td width="10"></td>
              <td><%# 滞在時間 %>
                  <% @attendance.each do |value| %>
                    <% departure_time = value[:departure] %>
                    <% arrival_time = value[:arrival] %>
                    <% if departure_time != nil %>
                      <%= ((departure_time - arrival_time) / 3600 ).round(2) if @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month  && departure_time.day == temp_day %>
                    <% end %>
                  <% end %>                
              </td>
              <td></td><td></td><td></td>
            </tr>
        <% end %>
        <td align="center" height="50" colspan="2"><%= 0.00 %></td>
        <td align="center" height="50" colspan="6"></td>
        <td align="center" height="50"><%# 滞在時間合計 %>
        <% total = 0 %>
          <% @attendance.each do |value| %>
            <% departure_time = value[:departure] %>
            <% arrival_time = value[:arrival] %>
            <% if departure_time != nil %>
              <% time_in_company = (departure_time - arrival_time) / 3600 %>
              <% total += time_in_company %>
            <% end %>
          <% end %>
          <%= total.round(2) if  @first_day.year == @y_m_d.year && @first_day.month == @y_m_d.month %>
        </td>
        <td align="center" height="50"></td>
        <td align="center" height="50"></td>
        <td align="center" height="50">所属長承認</td>
    </table> 
  </body>
</html>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール確認", @user %></span>
      <span><b>ツイート:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>